tipo_gasto:
  class: sfPropelRouteCollection
  options:
    model:               TipoGasto
    module:              tipo_gasto
    prefix_path:         tipo_gasto
    column:              id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
